### ISSUE TITLE
............

### ISSUE THREAD

**Issue by sam920829** [diwasatreya/Recluse-Bot#2]
ode
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/compiled/12.22.1/linux/x64/better_sqlite3.node
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/runner/Recluse-Bot/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/home/runner/Recluse-Bot/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/runner/Recluse-Bot/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Recluse-Bot/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  tries: [
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/compiled/12.22.1/linux/x64/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/runner/Recluse-Bot/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node'
  ]
}

**Comment by diwasatreya** [comment]
what application do you use for coding?

**Comment by sam920829** [comment]
replit.com

**Comment by sam920829** [comment]
.............

**Comment by diwasatreya** [comment]
Use the link below in read.md and fork it

**Comment by sam920829** [comment]
> Use the link below in readme.md and fork it

?????????????????

**Comment by sam920829** [comment]
App is listening to http://localhost:2323
(node:137) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/runner/Discord-Bot-Updated/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/home/runner/Discord-Bot-Updated/server.js:244:8)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by diwasatreya** [comment]
You have to put bot token in `.env` file or in repl.it Environment secret like TOKEN=maintoken or see video properly.

**Comment by sam920829** [comment]
> You have to put bot token in `.env` file or in repl.it Environment secret like TOKEN=maintoken or see video properly.
Bug after use
